name: poesiabat

on:
  schedule:
    - cron: '*/10 * * * *'
  
  workflow_dispatch:

jobs:
  poesiabatbot-post:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages(c("rtweet", "tidyverse"), dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript automatikoa_tw.R
      - name: Commit report
        run: |
          git config --global user.name 'MarLoi'
          git config --global user.email 'mloizate@uoc.edu'
          git commit -am "Automated report"
          git push
