name: poesiabat

on:
  schedule:
    - cron: '0,10 * * * *'

jobs:
  poesiabatbot-post:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rtweet package
        run: Rscript -e 'install.packages("rtweet", "tidyverse", dependencies = TRUE)'
      - name: Create and post tweet
        run: Rscript automatikoa_tw.R
